name: monitor-k8s CI/CD Pipiline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true  # Push the image to Docker Hub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest
              
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,ref,workflow,job,took
        env:
          SLACK_USERNAME: monitor-k8s-CI/CD
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
                   
        
