name: monitor-k8s CI/CD Pipiline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
              
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          channel: '#all-eaglebots'
          status: ${{ job.status }}
          message: Commit initiated...
          fields: repo,commit,author,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: monitor-k8s-CI/CD
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
                   
        
